//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Sample.Order.List
{
    public partial class OrderList
    {
        protected global::System.Web.UI.WebControls.Literal PageDescription;
        protected global::System.Web.UI.WebControls.DropDownList CategoryDropDown;
        protected global::System.Web.UI.WebControls.DropDownList OrderStatusDropDown;
        protected global::System.Web.UI.WebControls.DropDownList CustomerDropDown;
        protected global::System.Web.UI.WebControls.TextBox MinOrderTotalTextBox;
        protected global::System.Web.UI.WebControls.TextBox MaxOrderTotalTextBox;
        protected global::System.Web.UI.WebControls.TextBox MinQuantityTextBox;
        protected global::System.Web.UI.WebControls.Label DateRangeDropDownLabel;
        protected global::System.Web.UI.WebControls.DropDownList DateRangeDropDown;
        protected global::System.Web.UI.WebControls.Button SearchButton;
        protected global::System.Web.UI.WebControls.Literal CriteriaLiteral;
        protected global::System.Web.UI.WebControls.Literal InitialDataLiteral;
        protected global::System.Web.UI.WebControls.Literal PendingOrdersDataLiteral;
        protected global::System.Web.UI.WebControls.Literal QueueDataLiteral;
    }
}
